"""!
@file 
@brief function for movement in simulation
"""

import pygame
from Classes.Ball import Ball
from Classes.SoccerField import SoccerField
from Classes.SoccerRobot import SoccerRobot
from Constants import Const


# Move the player based on key pressed
def playerMovement(key: pygame.key, player: SoccerRobot):
    """!
    @brief player movements depending on what key is generated by the computer

    @param keys the key events that got pressed
    @param player the soccer robot that is being moved / moves

    @return void This function does not return a value.
    """
    if key == pygame.K_LEFT:
        player.currentDirection = Const.WEST_DIRECTION
    elif key == pygame.K_RIGHT:
        player.currentDirection = Const.EAST_DIRECTION
    elif key == pygame.K_UP:
        player.currentDirection = Const.NORTH_DIRECTION
    elif key == pygame.K_DOWN:
        player.currentDirection = Const.SOUTH_DIRECTION
    player.move()


def playerManualMove(keys, player: SoccerRobot):
    """!
    @brief player movements depending on what key is pressed

    @param keys the key events that got pressed
    @param player the soccer robot that is being moved / moves

    @return void This function does not return a value.
    """
    if keys[pygame.K_LEFT]:
        player.currentDirection = Const.WEST_DIRECTION
    elif keys[pygame.K_RIGHT]:
        player.currentDirection = Const.EAST_DIRECTION
    elif keys[pygame.K_UP]:
        player.currentDirection = Const.NORTH_DIRECTION
    elif keys[pygame.K_DOWN]:
        player.currentDirection = Const.SOUTH_DIRECTION
    player.move()


def playerCollideMove(player: SoccerRobot):
    """!
    @brief once a player has collided with another player, 
    move the player in opposite direction to prevent a "walk over"

    @param player, the current player that has the collision

    @return void This function does not return a value.
    """
    stepBack: float = 2.25
    playerDirection = player.currentDirection
    if playerDirection == Const.WEST_DIRECTION:
        player.currentDirection = Const.EAST_DIRECTION
        player.move(stepBack)
    elif playerDirection == Const.EAST_DIRECTION:
        player.currentDirection = Const.WEST_DIRECTION
        player.move(stepBack)
    elif playerDirection == Const.NORTH_DIRECTION:
        player.currentDirection = Const.SOUTH_DIRECTION
        player.move(stepBack)
    elif playerDirection == Const.SOUTH_DIRECTION:
        player.currentDirection = Const.NORTH_DIRECTION
        player.move(stepBack)


def ballMovement(keys: pygame.key, ball: Ball):
    """!
    @brief ball movements depending on what key is pressed

    @param keys the key events that got pressed
    @param ball the ball Object

    @return void This function does not return a value.
    """
    if keys[pygame.K_LEFT]:
        ball.move(Const.WEST_DIRECTION)
    elif keys[pygame.K_RIGHT]:
        ball.move(Const.EAST_DIRECTION)
    elif keys[pygame.K_UP]:
        ball.move(Const.NORTH_DIRECTION)
    elif keys[pygame.K_DOWN]:
        ball.move(Const.SOUTH_DIRECTION)
