# name of workflow
name: basic test

# the workflow will alwas from on ANY push of this repository
on: push

# Which jobs should be executed in ths workflow ?
jobs:
  mini-test:
    # run on a (certain) virtual maschine
    runs-on: ubuntu-latest
    # steps to take while runnig the jobs
    steps:
      - name: Set up Python 3.12
        with:
          python-version: "3.12"
        run: |
          python --version

      - name: Install pygame
        run: |
          python -m pip install --upgrade pip
          pip --version
          pip install pygame
