# name of workflow
name: basic test

# the workflow will alwas from on ANY push of this repository
on: push

# Which jobs should be executed in ths workflow ?
jobs:
  mini-test:
    # run on a (certain) virtual maschine
    runs-on: ubuntu-latest
    # steps to take while runnig the jobs
    steps:
      # fist of all, install python
      # "uses" references an action that has already been created
      # https://github.com/actions/setup-python
      - name: Set up Python 3.12
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
        run: |
          python --version

      # execute multiple commands to install pygame
      - name: Install pygame
        run: |
          python -m pip install --upgrade pip
          pip --version
          pip install pygame
          pip show pygame
